const List<String> cityList = [
  "New York",
  "Buffalo",
  "Rochester",
  "Yonkers",
  "Syracuse",
  "Albany",
  "New Rochelle",
  "Mount Vernon",
  "Schenectady",
  "Utica",
  "White Plains",
  "Hempstead",
  "Troy",
  "Niagara Falls",
  "Binghamton",
  "Freeport",
  "Valley Stream",
  "Los Angeles",
  "San Diego",
  "San Jose",
  "San Francisco",
  "Fresno",
  "Sacramento",
  "Long Beach",
  "Oakland",
  "Bakersfield",
  "Anaheim",
  "Santa Ana",
  "Riverside",
  "Stockton",
  "Chula Vista",
  "Irvine",
  "Fremont",
  "San Bernardino",
  "Modesto",
  "Fontana",
  "Oxnard",
  "Moreno Valley",
  "Huntington Beach",
  "Glendale",
  "Santa Clarita",
  "Garden Grove",
  "Oceanside",
  "Rancho Cucamonga",
  "Santa Rosa",
  "Ontario",
  "Lancaster",
  "Elk Grove",
  "Corona",
  "Palmdale",
  "Salinas",
  "Pomona",
  "Hayward",
  "Escondido",
  "Torrance",
  "Sunnyvale",
  "Orange",
  "Fullerton",
  "Pasadena",
  "Thousand Oaks",
  "Visalia",
  "Simi Valley",
  "Concord",
  "Roseville",
  "Victorville",
  "Santa Clara",
  "Vallejo",
  "Berkeley",
  "El Monte",
  "Downey",
  "Costa Mesa",
  "Inglewood",
  "Carlsbad",
  "San Buenaventura (Ventura)",
  "Fairfield",
  "West Covina",
  "Murrieta",
  "Richmond",
  "Norwalk",
  "Antioch",
  "Temecula",
  "Burbank",
  "Daly City",
  "Rialto",
  "Santa Maria",
  "El Cajon",
  "San Mateo",
  "Clovis",
  "Compton",
  "Jurupa Valley",
  "Vista",
  "South Gate",
  "Mission Viejo",
  "Vacaville",
  "Carson",
  "Hesperia",
  "Santa Monica",
  "Westminster",
  "Redding",
  "Santa Barbara",
  "Chico",
  "Newport Beach",
  "San Leandro",
  "San Marcos",
  "Whittier",
  "Hawthorne",
  "Citrus Heights",
  "Tracy",
  "Alhambra",
  "Livermore",
  "Buena Park",
  "Menifee",
  "Hemet",
  "Lakewood",
  "Merced",
  "Chino",
  "Indio",
  "Redwood City",
  "Lake Forest",
  "Napa",
  "Tustin",
  "Bellflower",
  "Mountain View",
  "Chino Hills",
  "Baldwin Park",
  "Alameda",
  "Upland",
  "San Ramon",
  "Folsom",
  "Pleasanton",
  "Union City",
  "Perris",
  "Manteca",
  "Lynwood",
  "Apple Valley",
  "Redlands",
  "Turlock",
  "Milpitas",
  "Redondo Beach",
  "Rancho Cordova",
  "Yorba Linda",
  "Palo Alto",
  "Davis",
  "Camarillo",
  "Walnut Creek",
  "Pittsburg",
  "South San Francisco",
  "Yuba City",
  "San Clemente",
  "Laguna Niguel",
  "Pico Rivera",
  "Montebello",
  "Lodi",
  "Madera",
  "Santa Cruz",
  "La Habra",
  "Encinitas",
  "Monterey Park",
  "Tulare",
  "Cupertino",
  "Gardena",
  "National City",
  "Rocklin",
  "Petaluma",
  "Huntington Park",
  "San Rafael",
  "La Mesa",
  "Arcadia",
  "Fountain Valley",
  "Diamond Bar",
  "Woodland",
  "Santee",
  "Lake Elsinore",
  "Porterville",
  "Paramount",
  "Eastvale",
  "Rosemead",
  "Hanford",
  "Highland",
  "Brentwood",
  "Novato",
  "Colton",
  "Cathedral City",
  "Delano",
  "Yucaipa",
  "Watsonville",
  "Placentia",
  "Glendora",
  "Gilroy",
  "Palm Desert",
  "Cerritos",
  "West Sacramento",
  "Aliso Viejo",
  "Poway",
  "La Mirada",
  "Rancho Santa Margarita",
  "Cypress",
  "Dublin",
  "Covina",
  "Azusa",
  "Palm Springs",
  "San Luis Obispo",
  "Ceres",
  "San Jacinto",
  "Lincoln",
  "Newark",
  "Lompoc",
  "El Centro",
  "Danville",
  "Bell Gardens",
  "Coachella",
  "Rancho Palos Verdes",
  "San Bruno",
  "Rohnert Park",
  "Brea",
  "La Puente",
  "Campbell",
  "San Gabriel",
  "Beaumont",
  "Morgan Hill",
  "Culver City",
  "Calexico",
  "Stanton",
  "La Quinta",
  "Pacifica",
  "Montclair",
  "Oakley",
  "Monrovia",
  "Los Banos",
  "Martinez",
  "Chicago",
  "Aurora",
  "Rockford",
  "Joliet",
  "Naperville",
  "Springfield",
  "Peoria",
  "Elgin",
  "Waukegan",
  "Cicero",
  "Champaign",
  "Bloomington",
  "Arlington Heights",
  "Evanston",
  "Decatur",
  "Schaumburg",
  "Bolingbrook",
  "Palatine",
  "Skokie",
  "Des Plaines",
  "Orland Park",
  "Tinley Park",
  "Oak Lawn",
  "Berwyn",
  "Mount Prospect",
  "Normal",
  "Wheaton",
  "Hoffman Estates",
  "Oak Park",
  "Downers Grove",
  "Elmhurst",
  "Glenview",
  "DeKalb",
  "Lombard",
  "Belleville",
  "Moline",
  "Buffalo Grove",
  "Bartlett",
  "Urbana",
  "Quincy",
  "Crystal Lake",
  "Plainfield",
  "Streamwood",
  "Carol Stream",
  "Romeoville",
  "Rock Island",
  "Hanover Park",
  "Carpentersville",
  "Wheeling",
  "Park Ridge",
  "Addison",
  "Calumet City",
  "Houston",
  "San Antonio",
  "Dallas",
  "Austin",
  "Fort Worth",
  "El Paso",
  "Arlington",
  "Corpus Christi",
  "Plano",
  "Laredo",
  "Lubbock",
  "Garland",
  "Irving",
  "Amarillo",
  "Grand Prairie",
  "Brownsville",
  "Pasadena",
  "McKinney",
  "Mesquite",
  "McAllen",
  "Killeen",
  "Frisco",
  "Waco",
  "Carrollton",
  "Denton",
  "Midland",
  "Abilene",
  "Beaumont",
  "Round Rock",
  "Odessa",
  "Wichita Falls",
  "Richardson",
  "Lewisville",
  "Tyler",
  "College Station",
  "Pearland",
  "San Angelo",
  "Allen",
  "League City",
  "Sugar Land",
  "Longview",
  "Edinburg",
  "Mission",
  "Bryan",
  "Baytown",
  "Pharr",
  "Temple",
  "Missouri City",
  "Flower Mound",
  "Harlingen",
  "North Richland Hills",
  "Victoria",
  "Conroe",
  "New Braunfels",
  "Mansfield",
  "Cedar Park",
  "Rowlett",
  "Port Arthur",
  "Euless",
  "Georgetown",
  "Pflugerville",
  "DeSoto",
  "San Marcos",
  "Grapevine",
  "Bedford",
  "Galveston",
  "Cedar Hill",
  "Texas City",
  "Wylie",
  "Haltom City",
  "Keller",
  "Coppell",
  "Rockwall",
  "Huntsville",
  "Duncanville",
  "Sherman",
  "The Colony",
  "Burleson",
  "Hurst",
  "Lancaster",
  "Texarkana",
  "Friendswood",
  "Weslaco",
  "Philadelphia",
  "Pittsburgh",
  "Allentown",
  "Erie",
  "Reading",
  "Scranton",
  "Bethlehem",
  "Lancaster",
  "Harrisburg",
  "Altoona",
  "York",
  "State College",
  "Wilkes-Barre",
  "Abbotsford",
  "Armstrong",
  "Burnaby",
  "Campbell River",
  "Castlegar",
  "Chilliwack",
  "Colwood",
  "Coquitlam",
  "Courtenay",
  "Cranbrook",
  "Dawson Creek",
  "Delta",
  "Duncan",
  "Enderby",
  "Fernie",
  "Fort St. John",
  "Grand Forks",
  "Greenwood",
  "Kamloops",
  "Kelowna",
  "Kimberley",
  "Langford",
  "Langley",
  "Maple Ridge",
  "Merritt",
  "Nanaimo",
  "Nelson",
  "New Westminster",
  "North Vancouver",
  "Parksville",
  "Penticton",
  "Pitt Meadows",
  "Port Alberni",
  "Port Coquitlam",
  "Port Moody",
  "Powell River",
  "Prince George",
  "Prince Rupert",
  "Quesnel",
  "Revelstoke",
  "Richmond",
  "Rossland",
  "Salmon Arm",
  "Surrey",
  "Terrace",
  "Trail",
  "Vancouver",
  "Vernon",
  "Victoria",
  "West Kelowna",
  "White Rock",
  "Williams Lake",
];
